steps:
#Enable Services
- id : 'Enable Services'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
     gcloud services enable cloudresourcemanager.googleapis.com
     gcloud services enable serviceusage.googleapis.com

#Build image
- id : 'Build Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/codecomp3-python-player', '.']
  
#Push image
- id : 'Push Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/codecomp3-python-player']
  
- id : ' Check & Create Bucket for Terraform'
  name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      PROJECT_ID=$(gcloud config get-value project)
      gsutil ls gs://${PROJECT_ID}-tf-infra || (gsutil mb gs://${PROJECT_ID}-tf-infra && gsutil versioning set on gs://${PROJECT_ID}-tf-infra)


- id: 'tf init'
  name: 'hashicorp/terraform:light'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*************** TERRAFORM INIT ******************"
      echo "*************************************************" 
      cd src_tf/
      terraform init

#Check & Create App Engine
- id : 'Check & Create App Engine'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
       gcloud app create --region="us-central" || echo "App Already Present"
       

#Deploy image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "--image-url=gcr.io/${PROJECT_ID}/codecomp3-python-player"]
  timeout: '1600s'
images:
- gcr.io/$PROJECT_ID/codecomp3-python-player