name: Setup GCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true


    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud projects list
        gcloud services enable cloudbuild.googleapis.com
        CLOUDBUILD_SA="$(gcloud projects describe  ${{ secrets.PROJECT_ID }} --format 'value(projectNumber)')@cloudbuild.gserviceaccount.com"
        gcloud projects add-iam-policy-binding  ${{ secrets.PROJECT_ID }} --member serviceAccount:$CLOUDBUILD_SA --role roles/owner
        gcloud components install beta --quiet
        gcloud beta builds triggers describe codecomp3-trigger --format="json" || (gcloud beta builds triggers create github --description="codecomp3-trigger" --repo-name=${{  github.event.repository.name }} --repo-owner=${{ github.actor }} --branch-pattern="^master$" --build-config=cloudbuild.yaml  --substitutions _PROJECT_ID=${{ secrets.PROJECT_ID}} && gcloud beta builds triggers run "codecomp3-trigger" --branch="master")


#           To Deploy to App Engine Directly
#           gcloud services enable appengine.googleapis.com
#           gcloud app create --region="us-central" || echo "App Already Present"
#           gcloud app deploy --quiet
          
